name: Deploy web app

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

#    - name: Building web app
#      uses: azure/appservice-build@v2

    - name: Cache virtual environment
      uses: actions/cache@v2
      env:
        cache-name: cache-poetry-packages
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        poetry config virtualenvs.in-project true
        
    - name:   Install dependencies
      run:    poetry install

    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "."
        startup-command: "./scripts/startup.sh"